# Generated by Django 4.2.6 on 2024-05-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='is_doctor',
        ),
    ]
