# Generated by Django 4.2.6 on 2024-05-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_userinformation_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='information',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
